version: "3.1"
services:
    web:
        container_name: web-www
        build: .
        ports: 
            - "8000:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
        restart: unless-stopped
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
    db:
        image: mysql:5.6
        container_name: web-mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: app_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
        ports:
            - 3306:3306
        restart: unless-stopped
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: web-phpmyadmin
        links: 
            - db:db
        ports:
            - 8001:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: admin
            UPLOAD_LIMIT: 300M
        restart: unless-stopped
volumes:
    persistent:
